version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=todo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - GOOGLE_OAUTH2_CLIENT_ID
      - GOOGLE_OAUTH2_CLIENT_SECRET
      - GOOGLE_OAUTH2_CALLBACK_URL
      - LINKEDIN_OAUTH2_CALLBACK_URL
      - DEBUG=True

  db:
    image: postgres:16.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres